/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as StoryRouteImport } from './routes/story'
import { Route as StartRouteImport } from './routes/start'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClaimYourBusinessRouteImport } from './routes/claim-your-business'
import { Route as BookRouteImport } from './routes/book'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportTokenRouteImport } from './routes/report.$token'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as AppRepRouteImport } from './routes/app.rep'
import { Route as AppRefillRouteImport } from './routes/app.refill'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as ApiRefillPortalRouteImport } from './routes/api.refill-portal'
import { Route as ApiRefillCheckoutRouteImport } from './routes/api.refill-checkout'
import { Route as AppRepIndexRouteImport } from './routes/app.rep.index'
import { Route as AppRefillIndexRouteImport } from './routes/app.refill.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as WaitlistOptinTokenRouteImport } from './routes/waitlist.optin.$token'
import { Route as RescueClaimTokenRouteImport } from './routes/rescue.claim.$token'
import { Route as AppRepReferralLinksRouteImport } from './routes/app.rep.referral-links'
import { Route as AppRepRecruitRouteImport } from './routes/app.rep.recruit'
import { Route as AppRepOutreachRouteImport } from './routes/app.rep.outreach'
import { Route as AppRepNetworkRouteImport } from './routes/app.rep.network'
import { Route as AppRepLedgerRouteImport } from './routes/app.rep.ledger'
import { Route as AppRepIntegrationsRouteImport } from './routes/app.rep.integrations'
import { Route as AppRepEconomicsRouteImport } from './routes/app.rep.economics'
import { Route as AppRefillSharingRouteImport } from './routes/app.refill.sharing'
import { Route as AppRefillRescueRouteImport } from './routes/app.refill.rescue'
import { Route as AppRefillReportsRouteImport } from './routes/app.refill.reports'
import { Route as AppRefillRecoveryRouteImport } from './routes/app.refill.recovery'
import { Route as AppRefillPromosRouteImport } from './routes/app.refill.promos'
import { Route as AppRefillPatientsRouteImport } from './routes/app.refill.patients'
import { Route as AppRefillInboxRouteImport } from './routes/app.refill.inbox'
import { Route as AppRefillHealthRouteImport } from './routes/app.refill.health'
import { Route as AppRefillCampaignsRouteImport } from './routes/app.refill.campaigns'
import { Route as AppRefillBillingRouteImport } from './routes/app.refill.billing'
import { Route as AppRefillAppointmentsRouteImport } from './routes/app.refill.appointments'
import { Route as AppAdminWishlistRouteImport } from './routes/app.admin.wishlist'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminReportsRouteImport } from './routes/app.admin.reports'
import { Route as AppAdminRefillTrialsRouteImport } from './routes/app.admin.refill-trials'
import { Route as AppAdminOutreachRouteImport } from './routes/app.admin.outreach'
import { Route as AppAdminFlagsRouteImport } from './routes/app.admin.flags'
import { Route as AppAdminCanonicalBrandsRouteImport } from './routes/app.admin.canonical-brands'
import { Route as AppAdminAuditRouteImport } from './routes/app.admin.audit'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api.webhooks.stripe'
import { Route as ApiTwilioInboundRouteImport } from './routes/api.twilio.inbound'
import { Route as ApiCronRefillTrialDripRouteImport } from './routes/api.cron.refill-trial-drip'
import { Route as ApiCronRefillInvoiceRouteImport } from './routes/api.cron.refill-invoice'
import { Route as ApiCronEmmaSweepRouteImport } from './routes/api.cron.emma-sweep'
import { Route as ApiCronEmmaReliabilitySweepRouteImport } from './routes/api.cron.emma-reliability-sweep'
import { Route as ApiCronEmmaReconcileRouteImport } from './routes/api.cron.emma-reconcile'
import { Route as ApiCronEmmaRecommendationsRouteImport } from './routes/api.cron.emma-recommendations'
import { Route as ApiCronEmmaPreshowSweepRouteImport } from './routes/api.cron.emma-preshow-sweep'
import { Route as ApiCronEmmaInvoiceRouteImport } from './routes/api.cron.emma-invoice'
import { Route as AppRefillPatientsIndexRouteImport } from './routes/app.refill.patients.index'
import { Route as AppRefillCampaignsIndexRouteImport } from './routes/app.refill.campaigns.index'
import { Route as AppRefillWaitlistSeedRouteImport } from './routes/app.refill.waitlist.seed'
import { Route as AppRefillWaitlistInviteRouteImport } from './routes/app.refill.waitlist.invite'
import { Route as AppRefillWaitlistBulkRouteImport } from './routes/app.refill.waitlist.bulk'
import { Route as AppRefillSettingsSpaProfileRouteImport } from './routes/app.refill.settings.spa-profile'
import { Route as AppRefillSettingsSenderRouteImport } from './routes/app.refill.settings.sender'
import { Route as AppRefillSettingsSchedulerRouteImport } from './routes/app.refill.settings.scheduler'
import { Route as AppRefillSettingsNoshowRouteImport } from './routes/app.refill.settings.noshow'
import { Route as AppRefillSettingsAccountRouteImport } from './routes/app.refill.settings.account'
import { Route as AppRefillPatientsImportRouteImport } from './routes/app.refill.patients.import'
import { Route as AppRefillPatientsContactsRouteImport } from './routes/app.refill.patients.contacts'
import { Route as AppRefillPatientsAListRulesRouteImport } from './routes/app.refill.patients.a-list-rules'
import { Route as AppRefillPatientsPatientIdRouteImport } from './routes/app.refill.patients.$patientId'
import { Route as AppRefillCatalogServicesRouteImport } from './routes/app.refill.catalog.services'
import { Route as AppRefillCatalogProductsRouteImport } from './routes/app.refill.catalog.products'
import { Route as AppRefillCatalogImportRouteImport } from './routes/app.refill.catalog.import'
import { Route as AppRefillCampaignsNewRouteImport } from './routes/app.refill.campaigns.new'
import { Route as AppRefillCampaignsCampaignIdRouteImport } from './routes/app.refill.campaigns.$campaignId'
import { Route as ApiIntegrationsAcuityOauthCallbackRouteImport } from './routes/api.integrations.acuity.oauth-callback'
import { Route as AppRefillCampaignsCampaignIdIndexRouteImport } from './routes/app.refill.campaigns.$campaignId.index'
import { Route as AppRefillCampaignsCampaignIdBlastRouteImport } from './routes/app.refill.campaigns.$campaignId.blast'
import { Route as ApiWebhooksSchedulerAcuitySecretRouteImport } from './routes/api.webhooks.scheduler.acuity.$secret'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimYourBusinessRoute = ClaimYourBusinessRouteImport.update({
  id: '/claim-your-business',
  path: '/claim-your-business',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportTokenRoute = ReportTokenRouteImport.update({
  id: '/report/$token',
  path: '/report/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRepRoute = AppRepRouteImport.update({
  id: '/rep',
  path: '/rep',
  getParentRoute: () => AppRoute,
} as any)
const AppRefillRoute = AppRefillRouteImport.update({
  id: '/refill',
  path: '/refill',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const ApiRefillPortalRoute = ApiRefillPortalRouteImport.update({
  id: '/api/refill-portal',
  path: '/api/refill-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRefillCheckoutRoute = ApiRefillCheckoutRouteImport.update({
  id: '/api/refill-checkout',
  path: '/api/refill-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRepIndexRoute = AppRepIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRepRoute,
} as any)
const AppRefillIndexRoute = AppRefillIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRefillRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const WaitlistOptinTokenRoute = WaitlistOptinTokenRouteImport.update({
  id: '/waitlist/optin/$token',
  path: '/waitlist/optin/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RescueClaimTokenRoute = RescueClaimTokenRouteImport.update({
  id: '/rescue/claim/$token',
  path: '/rescue/claim/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRepReferralLinksRoute = AppRepReferralLinksRouteImport.update({
  id: '/referral-links',
  path: '/referral-links',
  getParentRoute: () => AppRepRoute,
} as any)
const AppRepRecruitRoute = AppRepRecruitRouteImport.update({
  id: '/recruit',
  path: '/recruit',
  getParentRoute: () => AppRepRoute,
} as any)
const AppRepOutreachRoute = AppRepOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => AppRepRoute,
} as any)
const AppRepNetworkRoute = AppRepNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRepRoute,
} as any)
const AppRepLedgerRoute = AppRepLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppRepRoute,
} as any)
const AppRepIntegrationsRoute = AppRepIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRepRoute,
} as any)
const AppRepEconomicsRoute = AppRepEconomicsRouteImport.update({
  id: '/economics',
  path: '/economics',
  getParentRoute: () => AppRepRoute,
} as any)
const AppRefillSharingRoute = AppRefillSharingRouteImport.update({
  id: '/sharing',
  path: '/sharing',
  getParentRoute: () => AppRefillRoute,
} as any)
const AppRefillRescueRoute = AppRefillRescueRouteImport.update({
  id: '/rescue',
  path: '/rescue',
  getParentRoute: () => AppRefillRoute,
} as any)
const AppRefillReportsRoute = AppRefillReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRefillRoute,
} as any)
const AppRefillRecoveryRoute = AppRefillRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => AppRefillRoute,
} as any)
const AppRefillPromosRoute = AppRefillPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => AppRefillRoute,
} as any)
const AppRefillPatientsRoute = AppRefillPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRefillRoute,
} as any)
const AppRefillInboxRoute = AppRefillInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRefillRoute,
} as any)
const AppRefillHealthRoute = AppRefillHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRefillRoute,
} as any)
const AppRefillCampaignsRoute = AppRefillCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRefillRoute,
} as any)
const AppRefillBillingRoute = AppRefillBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRefillRoute,
} as any)
const AppRefillAppointmentsRoute = AppRefillAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRefillRoute,
} as any)
const AppAdminWishlistRoute = AppAdminWishlistRouteImport.update({
  id: '/admin/wishlist',
  path: '/admin/wishlist',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminReportsRoute = AppAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRefillTrialsRoute = AppAdminRefillTrialsRouteImport.update({
  id: '/admin/refill-trials',
  path: '/admin/refill-trials',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOutreachRoute = AppAdminOutreachRouteImport.update({
  id: '/admin/outreach',
  path: '/admin/outreach',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminFlagsRoute = AppAdminFlagsRouteImport.update({
  id: '/admin/flags',
  path: '/admin/flags',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCanonicalBrandsRoute = AppAdminCanonicalBrandsRouteImport.update({
  id: '/admin/canonical-brands',
  path: '/admin/canonical-brands',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AppRoute,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwilioInboundRoute = ApiTwilioInboundRouteImport.update({
  id: '/api/twilio/inbound',
  path: '/api/twilio/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRefillTrialDripRoute = ApiCronRefillTrialDripRouteImport.update({
  id: '/api/cron/refill-trial-drip',
  path: '/api/cron/refill-trial-drip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRefillInvoiceRoute = ApiCronRefillInvoiceRouteImport.update({
  id: '/api/cron/refill-invoice',
  path: '/api/cron/refill-invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronEmmaSweepRoute = ApiCronEmmaSweepRouteImport.update({
  id: '/api/cron/emma-sweep',
  path: '/api/cron/emma-sweep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronEmmaReliabilitySweepRoute =
  ApiCronEmmaReliabilitySweepRouteImport.update({
    id: '/api/cron/emma-reliability-sweep',
    path: '/api/cron/emma-reliability-sweep',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronEmmaReconcileRoute = ApiCronEmmaReconcileRouteImport.update({
  id: '/api/cron/emma-reconcile',
  path: '/api/cron/emma-reconcile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronEmmaRecommendationsRoute =
  ApiCronEmmaRecommendationsRouteImport.update({
    id: '/api/cron/emma-recommendations',
    path: '/api/cron/emma-recommendations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronEmmaPreshowSweepRoute = ApiCronEmmaPreshowSweepRouteImport.update({
  id: '/api/cron/emma-preshow-sweep',
  path: '/api/cron/emma-preshow-sweep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronEmmaInvoiceRoute = ApiCronEmmaInvoiceRouteImport.update({
  id: '/api/cron/emma-invoice',
  path: '/api/cron/emma-invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRefillPatientsIndexRoute = AppRefillPatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRefillPatientsRoute,
} as any)
const AppRefillCampaignsIndexRoute = AppRefillCampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRefillCampaignsRoute,
} as any)
const AppRefillWaitlistSeedRoute = AppRefillWaitlistSeedRouteImport.update({
  id: '/waitlist/seed',
  path: '/waitlist/seed',
  getParentRoute: () => AppRefillRoute,
} as any)
const AppRefillWaitlistInviteRoute = AppRefillWaitlistInviteRouteImport.update({
  id: '/waitlist/invite',
  path: '/waitlist/invite',
  getParentRoute: () => AppRefillRoute,
} as any)
const AppRefillWaitlistBulkRoute = AppRefillWaitlistBulkRouteImport.update({
  id: '/waitlist/bulk',
  path: '/waitlist/bulk',
  getParentRoute: () => AppRefillRoute,
} as any)
const AppRefillSettingsSpaProfileRoute =
  AppRefillSettingsSpaProfileRouteImport.update({
    id: '/settings/spa-profile',
    path: '/settings/spa-profile',
    getParentRoute: () => AppRefillRoute,
  } as any)
const AppRefillSettingsSenderRoute = AppRefillSettingsSenderRouteImport.update({
  id: '/settings/sender',
  path: '/settings/sender',
  getParentRoute: () => AppRefillRoute,
} as any)
const AppRefillSettingsSchedulerRoute =
  AppRefillSettingsSchedulerRouteImport.update({
    id: '/settings/scheduler',
    path: '/settings/scheduler',
    getParentRoute: () => AppRefillRoute,
  } as any)
const AppRefillSettingsNoshowRoute = AppRefillSettingsNoshowRouteImport.update({
  id: '/settings/noshow',
  path: '/settings/noshow',
  getParentRoute: () => AppRefillRoute,
} as any)
const AppRefillSettingsAccountRoute =
  AppRefillSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => AppRefillRoute,
  } as any)
const AppRefillPatientsImportRoute = AppRefillPatientsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRefillPatientsRoute,
} as any)
const AppRefillPatientsContactsRoute =
  AppRefillPatientsContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AppRefillPatientsRoute,
  } as any)
const AppRefillPatientsAListRulesRoute =
  AppRefillPatientsAListRulesRouteImport.update({
    id: '/a-list-rules',
    path: '/a-list-rules',
    getParentRoute: () => AppRefillPatientsRoute,
  } as any)
const AppRefillPatientsPatientIdRoute =
  AppRefillPatientsPatientIdRouteImport.update({
    id: '/$patientId',
    path: '/$patientId',
    getParentRoute: () => AppRefillPatientsRoute,
  } as any)
const AppRefillCatalogServicesRoute =
  AppRefillCatalogServicesRouteImport.update({
    id: '/catalog/services',
    path: '/catalog/services',
    getParentRoute: () => AppRefillRoute,
  } as any)
const AppRefillCatalogProductsRoute =
  AppRefillCatalogProductsRouteImport.update({
    id: '/catalog/products',
    path: '/catalog/products',
    getParentRoute: () => AppRefillRoute,
  } as any)
const AppRefillCatalogImportRoute = AppRefillCatalogImportRouteImport.update({
  id: '/catalog/import',
  path: '/catalog/import',
  getParentRoute: () => AppRefillRoute,
} as any)
const AppRefillCampaignsNewRoute = AppRefillCampaignsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRefillCampaignsRoute,
} as any)
const AppRefillCampaignsCampaignIdRoute =
  AppRefillCampaignsCampaignIdRouteImport.update({
    id: '/$campaignId',
    path: '/$campaignId',
    getParentRoute: () => AppRefillCampaignsRoute,
  } as any)
const ApiIntegrationsAcuityOauthCallbackRoute =
  ApiIntegrationsAcuityOauthCallbackRouteImport.update({
    id: '/api/integrations/acuity/oauth-callback',
    path: '/api/integrations/acuity/oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppRefillCampaignsCampaignIdIndexRoute =
  AppRefillCampaignsCampaignIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppRefillCampaignsCampaignIdRoute,
  } as any)
const AppRefillCampaignsCampaignIdBlastRoute =
  AppRefillCampaignsCampaignIdBlastRouteImport.update({
    id: '/blast',
    path: '/blast',
    getParentRoute: () => AppRefillCampaignsCampaignIdRoute,
  } as any)
const ApiWebhooksSchedulerAcuitySecretRoute =
  ApiWebhooksSchedulerAcuitySecretRouteImport.update({
    id: '/api/webhooks/scheduler/acuity/$secret',
    path: '/api/webhooks/scheduler/acuity/$secret',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/book': typeof BookRoute
  '/claim-your-business': typeof ClaimYourBusinessRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/start': typeof StartRoute
  '/story': typeof StoryRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/api/refill-checkout': typeof ApiRefillCheckoutRoute
  '/api/refill-portal': typeof ApiRefillPortalRoute
  '/app/billing': typeof AppBillingRoute
  '/app/refill': typeof AppRefillRouteWithChildren
  '/app/rep': typeof AppRepRouteWithChildren
  '/r/$slug': typeof RSlugRoute
  '/report/$token': typeof ReportTokenRoute
  '/api/cron/emma-invoice': typeof ApiCronEmmaInvoiceRoute
  '/api/cron/emma-preshow-sweep': typeof ApiCronEmmaPreshowSweepRoute
  '/api/cron/emma-recommendations': typeof ApiCronEmmaRecommendationsRoute
  '/api/cron/emma-reconcile': typeof ApiCronEmmaReconcileRoute
  '/api/cron/emma-reliability-sweep': typeof ApiCronEmmaReliabilitySweepRoute
  '/api/cron/emma-sweep': typeof ApiCronEmmaSweepRoute
  '/api/cron/refill-invoice': typeof ApiCronRefillInvoiceRoute
  '/api/cron/refill-trial-drip': typeof ApiCronRefillTrialDripRoute
  '/api/twilio/inbound': typeof ApiTwilioInboundRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/canonical-brands': typeof AppAdminCanonicalBrandsRoute
  '/app/admin/flags': typeof AppAdminFlagsRoute
  '/app/admin/outreach': typeof AppAdminOutreachRoute
  '/app/admin/refill-trials': typeof AppAdminRefillTrialsRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/wishlist': typeof AppAdminWishlistRoute
  '/app/refill/appointments': typeof AppRefillAppointmentsRoute
  '/app/refill/billing': typeof AppRefillBillingRoute
  '/app/refill/campaigns': typeof AppRefillCampaignsRouteWithChildren
  '/app/refill/health': typeof AppRefillHealthRoute
  '/app/refill/inbox': typeof AppRefillInboxRoute
  '/app/refill/patients': typeof AppRefillPatientsRouteWithChildren
  '/app/refill/promos': typeof AppRefillPromosRoute
  '/app/refill/recovery': typeof AppRefillRecoveryRoute
  '/app/refill/reports': typeof AppRefillReportsRoute
  '/app/refill/rescue': typeof AppRefillRescueRoute
  '/app/refill/sharing': typeof AppRefillSharingRoute
  '/app/rep/economics': typeof AppRepEconomicsRoute
  '/app/rep/integrations': typeof AppRepIntegrationsRoute
  '/app/rep/ledger': typeof AppRepLedgerRoute
  '/app/rep/network': typeof AppRepNetworkRoute
  '/app/rep/outreach': typeof AppRepOutreachRoute
  '/app/rep/recruit': typeof AppRepRecruitRoute
  '/app/rep/referral-links': typeof AppRepReferralLinksRoute
  '/rescue/claim/$token': typeof RescueClaimTokenRoute
  '/waitlist/optin/$token': typeof WaitlistOptinTokenRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/refill/': typeof AppRefillIndexRoute
  '/app/rep/': typeof AppRepIndexRoute
  '/api/integrations/acuity/oauth-callback': typeof ApiIntegrationsAcuityOauthCallbackRoute
  '/app/refill/campaigns/$campaignId': typeof AppRefillCampaignsCampaignIdRouteWithChildren
  '/app/refill/campaigns/new': typeof AppRefillCampaignsNewRoute
  '/app/refill/catalog/import': typeof AppRefillCatalogImportRoute
  '/app/refill/catalog/products': typeof AppRefillCatalogProductsRoute
  '/app/refill/catalog/services': typeof AppRefillCatalogServicesRoute
  '/app/refill/patients/$patientId': typeof AppRefillPatientsPatientIdRoute
  '/app/refill/patients/a-list-rules': typeof AppRefillPatientsAListRulesRoute
  '/app/refill/patients/contacts': typeof AppRefillPatientsContactsRoute
  '/app/refill/patients/import': typeof AppRefillPatientsImportRoute
  '/app/refill/settings/account': typeof AppRefillSettingsAccountRoute
  '/app/refill/settings/noshow': typeof AppRefillSettingsNoshowRoute
  '/app/refill/settings/scheduler': typeof AppRefillSettingsSchedulerRoute
  '/app/refill/settings/sender': typeof AppRefillSettingsSenderRoute
  '/app/refill/settings/spa-profile': typeof AppRefillSettingsSpaProfileRoute
  '/app/refill/waitlist/bulk': typeof AppRefillWaitlistBulkRoute
  '/app/refill/waitlist/invite': typeof AppRefillWaitlistInviteRoute
  '/app/refill/waitlist/seed': typeof AppRefillWaitlistSeedRoute
  '/app/refill/campaigns/': typeof AppRefillCampaignsIndexRoute
  '/app/refill/patients/': typeof AppRefillPatientsIndexRoute
  '/api/webhooks/scheduler/acuity/$secret': typeof ApiWebhooksSchedulerAcuitySecretRoute
  '/app/refill/campaigns/$campaignId/blast': typeof AppRefillCampaignsCampaignIdBlastRoute
  '/app/refill/campaigns/$campaignId/': typeof AppRefillCampaignsCampaignIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/book': typeof BookRoute
  '/claim-your-business': typeof ClaimYourBusinessRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/start': typeof StartRoute
  '/story': typeof StoryRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/api/refill-checkout': typeof ApiRefillCheckoutRoute
  '/api/refill-portal': typeof ApiRefillPortalRoute
  '/app/billing': typeof AppBillingRoute
  '/r/$slug': typeof RSlugRoute
  '/report/$token': typeof ReportTokenRoute
  '/api/cron/emma-invoice': typeof ApiCronEmmaInvoiceRoute
  '/api/cron/emma-preshow-sweep': typeof ApiCronEmmaPreshowSweepRoute
  '/api/cron/emma-recommendations': typeof ApiCronEmmaRecommendationsRoute
  '/api/cron/emma-reconcile': typeof ApiCronEmmaReconcileRoute
  '/api/cron/emma-reliability-sweep': typeof ApiCronEmmaReliabilitySweepRoute
  '/api/cron/emma-sweep': typeof ApiCronEmmaSweepRoute
  '/api/cron/refill-invoice': typeof ApiCronRefillInvoiceRoute
  '/api/cron/refill-trial-drip': typeof ApiCronRefillTrialDripRoute
  '/api/twilio/inbound': typeof ApiTwilioInboundRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/canonical-brands': typeof AppAdminCanonicalBrandsRoute
  '/app/admin/flags': typeof AppAdminFlagsRoute
  '/app/admin/outreach': typeof AppAdminOutreachRoute
  '/app/admin/refill-trials': typeof AppAdminRefillTrialsRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/wishlist': typeof AppAdminWishlistRoute
  '/app/refill/appointments': typeof AppRefillAppointmentsRoute
  '/app/refill/billing': typeof AppRefillBillingRoute
  '/app/refill/health': typeof AppRefillHealthRoute
  '/app/refill/inbox': typeof AppRefillInboxRoute
  '/app/refill/promos': typeof AppRefillPromosRoute
  '/app/refill/recovery': typeof AppRefillRecoveryRoute
  '/app/refill/reports': typeof AppRefillReportsRoute
  '/app/refill/rescue': typeof AppRefillRescueRoute
  '/app/refill/sharing': typeof AppRefillSharingRoute
  '/app/rep/economics': typeof AppRepEconomicsRoute
  '/app/rep/integrations': typeof AppRepIntegrationsRoute
  '/app/rep/ledger': typeof AppRepLedgerRoute
  '/app/rep/network': typeof AppRepNetworkRoute
  '/app/rep/outreach': typeof AppRepOutreachRoute
  '/app/rep/recruit': typeof AppRepRecruitRoute
  '/app/rep/referral-links': typeof AppRepReferralLinksRoute
  '/rescue/claim/$token': typeof RescueClaimTokenRoute
  '/waitlist/optin/$token': typeof WaitlistOptinTokenRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/refill': typeof AppRefillIndexRoute
  '/app/rep': typeof AppRepIndexRoute
  '/api/integrations/acuity/oauth-callback': typeof ApiIntegrationsAcuityOauthCallbackRoute
  '/app/refill/campaigns/new': typeof AppRefillCampaignsNewRoute
  '/app/refill/catalog/import': typeof AppRefillCatalogImportRoute
  '/app/refill/catalog/products': typeof AppRefillCatalogProductsRoute
  '/app/refill/catalog/services': typeof AppRefillCatalogServicesRoute
  '/app/refill/patients/$patientId': typeof AppRefillPatientsPatientIdRoute
  '/app/refill/patients/a-list-rules': typeof AppRefillPatientsAListRulesRoute
  '/app/refill/patients/contacts': typeof AppRefillPatientsContactsRoute
  '/app/refill/patients/import': typeof AppRefillPatientsImportRoute
  '/app/refill/settings/account': typeof AppRefillSettingsAccountRoute
  '/app/refill/settings/noshow': typeof AppRefillSettingsNoshowRoute
  '/app/refill/settings/scheduler': typeof AppRefillSettingsSchedulerRoute
  '/app/refill/settings/sender': typeof AppRefillSettingsSenderRoute
  '/app/refill/settings/spa-profile': typeof AppRefillSettingsSpaProfileRoute
  '/app/refill/waitlist/bulk': typeof AppRefillWaitlistBulkRoute
  '/app/refill/waitlist/invite': typeof AppRefillWaitlistInviteRoute
  '/app/refill/waitlist/seed': typeof AppRefillWaitlistSeedRoute
  '/app/refill/campaigns': typeof AppRefillCampaignsIndexRoute
  '/app/refill/patients': typeof AppRefillPatientsIndexRoute
  '/api/webhooks/scheduler/acuity/$secret': typeof ApiWebhooksSchedulerAcuitySecretRoute
  '/app/refill/campaigns/$campaignId/blast': typeof AppRefillCampaignsCampaignIdBlastRoute
  '/app/refill/campaigns/$campaignId': typeof AppRefillCampaignsCampaignIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/book': typeof BookRoute
  '/claim-your-business': typeof ClaimYourBusinessRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/start': typeof StartRoute
  '/story': typeof StoryRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/api/refill-checkout': typeof ApiRefillCheckoutRoute
  '/api/refill-portal': typeof ApiRefillPortalRoute
  '/app/billing': typeof AppBillingRoute
  '/app/refill': typeof AppRefillRouteWithChildren
  '/app/rep': typeof AppRepRouteWithChildren
  '/r/$slug': typeof RSlugRoute
  '/report/$token': typeof ReportTokenRoute
  '/api/cron/emma-invoice': typeof ApiCronEmmaInvoiceRoute
  '/api/cron/emma-preshow-sweep': typeof ApiCronEmmaPreshowSweepRoute
  '/api/cron/emma-recommendations': typeof ApiCronEmmaRecommendationsRoute
  '/api/cron/emma-reconcile': typeof ApiCronEmmaReconcileRoute
  '/api/cron/emma-reliability-sweep': typeof ApiCronEmmaReliabilitySweepRoute
  '/api/cron/emma-sweep': typeof ApiCronEmmaSweepRoute
  '/api/cron/refill-invoice': typeof ApiCronRefillInvoiceRoute
  '/api/cron/refill-trial-drip': typeof ApiCronRefillTrialDripRoute
  '/api/twilio/inbound': typeof ApiTwilioInboundRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/canonical-brands': typeof AppAdminCanonicalBrandsRoute
  '/app/admin/flags': typeof AppAdminFlagsRoute
  '/app/admin/outreach': typeof AppAdminOutreachRoute
  '/app/admin/refill-trials': typeof AppAdminRefillTrialsRoute
  '/app/admin/reports': typeof AppAdminReportsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/wishlist': typeof AppAdminWishlistRoute
  '/app/refill/appointments': typeof AppRefillAppointmentsRoute
  '/app/refill/billing': typeof AppRefillBillingRoute
  '/app/refill/campaigns': typeof AppRefillCampaignsRouteWithChildren
  '/app/refill/health': typeof AppRefillHealthRoute
  '/app/refill/inbox': typeof AppRefillInboxRoute
  '/app/refill/patients': typeof AppRefillPatientsRouteWithChildren
  '/app/refill/promos': typeof AppRefillPromosRoute
  '/app/refill/recovery': typeof AppRefillRecoveryRoute
  '/app/refill/reports': typeof AppRefillReportsRoute
  '/app/refill/rescue': typeof AppRefillRescueRoute
  '/app/refill/sharing': typeof AppRefillSharingRoute
  '/app/rep/economics': typeof AppRepEconomicsRoute
  '/app/rep/integrations': typeof AppRepIntegrationsRoute
  '/app/rep/ledger': typeof AppRepLedgerRoute
  '/app/rep/network': typeof AppRepNetworkRoute
  '/app/rep/outreach': typeof AppRepOutreachRoute
  '/app/rep/recruit': typeof AppRepRecruitRoute
  '/app/rep/referral-links': typeof AppRepReferralLinksRoute
  '/rescue/claim/$token': typeof RescueClaimTokenRoute
  '/waitlist/optin/$token': typeof WaitlistOptinTokenRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/refill/': typeof AppRefillIndexRoute
  '/app/rep/': typeof AppRepIndexRoute
  '/api/integrations/acuity/oauth-callback': typeof ApiIntegrationsAcuityOauthCallbackRoute
  '/app/refill/campaigns/$campaignId': typeof AppRefillCampaignsCampaignIdRouteWithChildren
  '/app/refill/campaigns/new': typeof AppRefillCampaignsNewRoute
  '/app/refill/catalog/import': typeof AppRefillCatalogImportRoute
  '/app/refill/catalog/products': typeof AppRefillCatalogProductsRoute
  '/app/refill/catalog/services': typeof AppRefillCatalogServicesRoute
  '/app/refill/patients/$patientId': typeof AppRefillPatientsPatientIdRoute
  '/app/refill/patients/a-list-rules': typeof AppRefillPatientsAListRulesRoute
  '/app/refill/patients/contacts': typeof AppRefillPatientsContactsRoute
  '/app/refill/patients/import': typeof AppRefillPatientsImportRoute
  '/app/refill/settings/account': typeof AppRefillSettingsAccountRoute
  '/app/refill/settings/noshow': typeof AppRefillSettingsNoshowRoute
  '/app/refill/settings/scheduler': typeof AppRefillSettingsSchedulerRoute
  '/app/refill/settings/sender': typeof AppRefillSettingsSenderRoute
  '/app/refill/settings/spa-profile': typeof AppRefillSettingsSpaProfileRoute
  '/app/refill/waitlist/bulk': typeof AppRefillWaitlistBulkRoute
  '/app/refill/waitlist/invite': typeof AppRefillWaitlistInviteRoute
  '/app/refill/waitlist/seed': typeof AppRefillWaitlistSeedRoute
  '/app/refill/campaigns/': typeof AppRefillCampaignsIndexRoute
  '/app/refill/patients/': typeof AppRefillPatientsIndexRoute
  '/api/webhooks/scheduler/acuity/$secret': typeof ApiWebhooksSchedulerAcuitySecretRoute
  '/app/refill/campaigns/$campaignId/blast': typeof AppRefillCampaignsCampaignIdBlastRoute
  '/app/refill/campaigns/$campaignId/': typeof AppRefillCampaignsCampaignIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/book'
    | '/claim-your-business'
    | '/login'
    | '/onboard'
    | '/pricing'
    | '/reset-password'
    | '/scan'
    | '/start'
    | '/story'
    | '/unsubscribe'
    | '/api/refill-checkout'
    | '/api/refill-portal'
    | '/app/billing'
    | '/app/refill'
    | '/app/rep'
    | '/r/$slug'
    | '/report/$token'
    | '/api/cron/emma-invoice'
    | '/api/cron/emma-preshow-sweep'
    | '/api/cron/emma-recommendations'
    | '/api/cron/emma-reconcile'
    | '/api/cron/emma-reliability-sweep'
    | '/api/cron/emma-sweep'
    | '/api/cron/refill-invoice'
    | '/api/cron/refill-trial-drip'
    | '/api/twilio/inbound'
    | '/api/webhooks/stripe'
    | '/app/admin/audit'
    | '/app/admin/canonical-brands'
    | '/app/admin/flags'
    | '/app/admin/outreach'
    | '/app/admin/refill-trials'
    | '/app/admin/reports'
    | '/app/admin/users'
    | '/app/admin/wishlist'
    | '/app/refill/appointments'
    | '/app/refill/billing'
    | '/app/refill/campaigns'
    | '/app/refill/health'
    | '/app/refill/inbox'
    | '/app/refill/patients'
    | '/app/refill/promos'
    | '/app/refill/recovery'
    | '/app/refill/reports'
    | '/app/refill/rescue'
    | '/app/refill/sharing'
    | '/app/rep/economics'
    | '/app/rep/integrations'
    | '/app/rep/ledger'
    | '/app/rep/network'
    | '/app/rep/outreach'
    | '/app/rep/recruit'
    | '/app/rep/referral-links'
    | '/rescue/claim/$token'
    | '/waitlist/optin/$token'
    | '/app/admin/'
    | '/app/refill/'
    | '/app/rep/'
    | '/api/integrations/acuity/oauth-callback'
    | '/app/refill/campaigns/$campaignId'
    | '/app/refill/campaigns/new'
    | '/app/refill/catalog/import'
    | '/app/refill/catalog/products'
    | '/app/refill/catalog/services'
    | '/app/refill/patients/$patientId'
    | '/app/refill/patients/a-list-rules'
    | '/app/refill/patients/contacts'
    | '/app/refill/patients/import'
    | '/app/refill/settings/account'
    | '/app/refill/settings/noshow'
    | '/app/refill/settings/scheduler'
    | '/app/refill/settings/sender'
    | '/app/refill/settings/spa-profile'
    | '/app/refill/waitlist/bulk'
    | '/app/refill/waitlist/invite'
    | '/app/refill/waitlist/seed'
    | '/app/refill/campaigns/'
    | '/app/refill/patients/'
    | '/api/webhooks/scheduler/acuity/$secret'
    | '/app/refill/campaigns/$campaignId/blast'
    | '/app/refill/campaigns/$campaignId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/book'
    | '/claim-your-business'
    | '/login'
    | '/onboard'
    | '/pricing'
    | '/reset-password'
    | '/scan'
    | '/start'
    | '/story'
    | '/unsubscribe'
    | '/api/refill-checkout'
    | '/api/refill-portal'
    | '/app/billing'
    | '/r/$slug'
    | '/report/$token'
    | '/api/cron/emma-invoice'
    | '/api/cron/emma-preshow-sweep'
    | '/api/cron/emma-recommendations'
    | '/api/cron/emma-reconcile'
    | '/api/cron/emma-reliability-sweep'
    | '/api/cron/emma-sweep'
    | '/api/cron/refill-invoice'
    | '/api/cron/refill-trial-drip'
    | '/api/twilio/inbound'
    | '/api/webhooks/stripe'
    | '/app/admin/audit'
    | '/app/admin/canonical-brands'
    | '/app/admin/flags'
    | '/app/admin/outreach'
    | '/app/admin/refill-trials'
    | '/app/admin/reports'
    | '/app/admin/users'
    | '/app/admin/wishlist'
    | '/app/refill/appointments'
    | '/app/refill/billing'
    | '/app/refill/health'
    | '/app/refill/inbox'
    | '/app/refill/promos'
    | '/app/refill/recovery'
    | '/app/refill/reports'
    | '/app/refill/rescue'
    | '/app/refill/sharing'
    | '/app/rep/economics'
    | '/app/rep/integrations'
    | '/app/rep/ledger'
    | '/app/rep/network'
    | '/app/rep/outreach'
    | '/app/rep/recruit'
    | '/app/rep/referral-links'
    | '/rescue/claim/$token'
    | '/waitlist/optin/$token'
    | '/app/admin'
    | '/app/refill'
    | '/app/rep'
    | '/api/integrations/acuity/oauth-callback'
    | '/app/refill/campaigns/new'
    | '/app/refill/catalog/import'
    | '/app/refill/catalog/products'
    | '/app/refill/catalog/services'
    | '/app/refill/patients/$patientId'
    | '/app/refill/patients/a-list-rules'
    | '/app/refill/patients/contacts'
    | '/app/refill/patients/import'
    | '/app/refill/settings/account'
    | '/app/refill/settings/noshow'
    | '/app/refill/settings/scheduler'
    | '/app/refill/settings/sender'
    | '/app/refill/settings/spa-profile'
    | '/app/refill/waitlist/bulk'
    | '/app/refill/waitlist/invite'
    | '/app/refill/waitlist/seed'
    | '/app/refill/campaigns'
    | '/app/refill/patients'
    | '/api/webhooks/scheduler/acuity/$secret'
    | '/app/refill/campaigns/$campaignId/blast'
    | '/app/refill/campaigns/$campaignId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/book'
    | '/claim-your-business'
    | '/login'
    | '/onboard'
    | '/pricing'
    | '/reset-password'
    | '/scan'
    | '/start'
    | '/story'
    | '/unsubscribe'
    | '/api/refill-checkout'
    | '/api/refill-portal'
    | '/app/billing'
    | '/app/refill'
    | '/app/rep'
    | '/r/$slug'
    | '/report/$token'
    | '/api/cron/emma-invoice'
    | '/api/cron/emma-preshow-sweep'
    | '/api/cron/emma-recommendations'
    | '/api/cron/emma-reconcile'
    | '/api/cron/emma-reliability-sweep'
    | '/api/cron/emma-sweep'
    | '/api/cron/refill-invoice'
    | '/api/cron/refill-trial-drip'
    | '/api/twilio/inbound'
    | '/api/webhooks/stripe'
    | '/app/admin/audit'
    | '/app/admin/canonical-brands'
    | '/app/admin/flags'
    | '/app/admin/outreach'
    | '/app/admin/refill-trials'
    | '/app/admin/reports'
    | '/app/admin/users'
    | '/app/admin/wishlist'
    | '/app/refill/appointments'
    | '/app/refill/billing'
    | '/app/refill/campaigns'
    | '/app/refill/health'
    | '/app/refill/inbox'
    | '/app/refill/patients'
    | '/app/refill/promos'
    | '/app/refill/recovery'
    | '/app/refill/reports'
    | '/app/refill/rescue'
    | '/app/refill/sharing'
    | '/app/rep/economics'
    | '/app/rep/integrations'
    | '/app/rep/ledger'
    | '/app/rep/network'
    | '/app/rep/outreach'
    | '/app/rep/recruit'
    | '/app/rep/referral-links'
    | '/rescue/claim/$token'
    | '/waitlist/optin/$token'
    | '/app/admin/'
    | '/app/refill/'
    | '/app/rep/'
    | '/api/integrations/acuity/oauth-callback'
    | '/app/refill/campaigns/$campaignId'
    | '/app/refill/campaigns/new'
    | '/app/refill/catalog/import'
    | '/app/refill/catalog/products'
    | '/app/refill/catalog/services'
    | '/app/refill/patients/$patientId'
    | '/app/refill/patients/a-list-rules'
    | '/app/refill/patients/contacts'
    | '/app/refill/patients/import'
    | '/app/refill/settings/account'
    | '/app/refill/settings/noshow'
    | '/app/refill/settings/scheduler'
    | '/app/refill/settings/sender'
    | '/app/refill/settings/spa-profile'
    | '/app/refill/waitlist/bulk'
    | '/app/refill/waitlist/invite'
    | '/app/refill/waitlist/seed'
    | '/app/refill/campaigns/'
    | '/app/refill/patients/'
    | '/api/webhooks/scheduler/acuity/$secret'
    | '/app/refill/campaigns/$campaignId/blast'
    | '/app/refill/campaigns/$campaignId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BookRoute: typeof BookRoute
  ClaimYourBusinessRoute: typeof ClaimYourBusinessRoute
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScanRoute: typeof ScanRoute
  StartRoute: typeof StartRoute
  StoryRoute: typeof StoryRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ApiRefillCheckoutRoute: typeof ApiRefillCheckoutRoute
  ApiRefillPortalRoute: typeof ApiRefillPortalRoute
  RSlugRoute: typeof RSlugRoute
  ReportTokenRoute: typeof ReportTokenRoute
  ApiCronEmmaInvoiceRoute: typeof ApiCronEmmaInvoiceRoute
  ApiCronEmmaPreshowSweepRoute: typeof ApiCronEmmaPreshowSweepRoute
  ApiCronEmmaRecommendationsRoute: typeof ApiCronEmmaRecommendationsRoute
  ApiCronEmmaReconcileRoute: typeof ApiCronEmmaReconcileRoute
  ApiCronEmmaReliabilitySweepRoute: typeof ApiCronEmmaReliabilitySweepRoute
  ApiCronEmmaSweepRoute: typeof ApiCronEmmaSweepRoute
  ApiCronRefillInvoiceRoute: typeof ApiCronRefillInvoiceRoute
  ApiCronRefillTrialDripRoute: typeof ApiCronRefillTrialDripRoute
  ApiTwilioInboundRoute: typeof ApiTwilioInboundRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  RescueClaimTokenRoute: typeof RescueClaimTokenRoute
  WaitlistOptinTokenRoute: typeof WaitlistOptinTokenRoute
  ApiIntegrationsAcuityOauthCallbackRoute: typeof ApiIntegrationsAcuityOauthCallbackRoute
  ApiWebhooksSchedulerAcuitySecretRoute: typeof ApiWebhooksSchedulerAcuitySecretRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim-your-business': {
      id: '/claim-your-business'
      path: '/claim-your-business'
      fullPath: '/claim-your-business'
      preLoaderRoute: typeof ClaimYourBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$token': {
      id: '/report/$token'
      path: '/report/$token'
      fullPath: '/report/$token'
      preLoaderRoute: typeof ReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rep': {
      id: '/app/rep'
      path: '/rep'
      fullPath: '/app/rep'
      preLoaderRoute: typeof AppRepRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/refill': {
      id: '/app/refill'
      path: '/refill'
      fullPath: '/app/refill'
      preLoaderRoute: typeof AppRefillRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/refill-portal': {
      id: '/api/refill-portal'
      path: '/api/refill-portal'
      fullPath: '/api/refill-portal'
      preLoaderRoute: typeof ApiRefillPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/refill-checkout': {
      id: '/api/refill-checkout'
      path: '/api/refill-checkout'
      fullPath: '/api/refill-checkout'
      preLoaderRoute: typeof ApiRefillCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rep/': {
      id: '/app/rep/'
      path: '/'
      fullPath: '/app/rep/'
      preLoaderRoute: typeof AppRepIndexRouteImport
      parentRoute: typeof AppRepRoute
    }
    '/app/refill/': {
      id: '/app/refill/'
      path: '/'
      fullPath: '/app/refill/'
      preLoaderRoute: typeof AppRefillIndexRouteImport
      parentRoute: typeof AppRefillRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/waitlist/optin/$token': {
      id: '/waitlist/optin/$token'
      path: '/waitlist/optin/$token'
      fullPath: '/waitlist/optin/$token'
      preLoaderRoute: typeof WaitlistOptinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rescue/claim/$token': {
      id: '/rescue/claim/$token'
      path: '/rescue/claim/$token'
      fullPath: '/rescue/claim/$token'
      preLoaderRoute: typeof RescueClaimTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rep/referral-links': {
      id: '/app/rep/referral-links'
      path: '/referral-links'
      fullPath: '/app/rep/referral-links'
      preLoaderRoute: typeof AppRepReferralLinksRouteImport
      parentRoute: typeof AppRepRoute
    }
    '/app/rep/recruit': {
      id: '/app/rep/recruit'
      path: '/recruit'
      fullPath: '/app/rep/recruit'
      preLoaderRoute: typeof AppRepRecruitRouteImport
      parentRoute: typeof AppRepRoute
    }
    '/app/rep/outreach': {
      id: '/app/rep/outreach'
      path: '/outreach'
      fullPath: '/app/rep/outreach'
      preLoaderRoute: typeof AppRepOutreachRouteImport
      parentRoute: typeof AppRepRoute
    }
    '/app/rep/network': {
      id: '/app/rep/network'
      path: '/network'
      fullPath: '/app/rep/network'
      preLoaderRoute: typeof AppRepNetworkRouteImport
      parentRoute: typeof AppRepRoute
    }
    '/app/rep/ledger': {
      id: '/app/rep/ledger'
      path: '/ledger'
      fullPath: '/app/rep/ledger'
      preLoaderRoute: typeof AppRepLedgerRouteImport
      parentRoute: typeof AppRepRoute
    }
    '/app/rep/integrations': {
      id: '/app/rep/integrations'
      path: '/integrations'
      fullPath: '/app/rep/integrations'
      preLoaderRoute: typeof AppRepIntegrationsRouteImport
      parentRoute: typeof AppRepRoute
    }
    '/app/rep/economics': {
      id: '/app/rep/economics'
      path: '/economics'
      fullPath: '/app/rep/economics'
      preLoaderRoute: typeof AppRepEconomicsRouteImport
      parentRoute: typeof AppRepRoute
    }
    '/app/refill/sharing': {
      id: '/app/refill/sharing'
      path: '/sharing'
      fullPath: '/app/refill/sharing'
      preLoaderRoute: typeof AppRefillSharingRouteImport
      parentRoute: typeof AppRefillRoute
    }
    '/app/refill/rescue': {
      id: '/app/refill/rescue'
      path: '/rescue'
      fullPath: '/app/refill/rescue'
      preLoaderRoute: typeof AppRefillRescueRouteImport
      parentRoute: typeof AppRefillRoute
    }
    '/app/refill/reports': {
      id: '/app/refill/reports'
      path: '/reports'
      fullPath: '/app/refill/reports'
      preLoaderRoute: typeof AppRefillReportsRouteImport
      parentRoute: typeof AppRefillRoute
    }
    '/app/refill/recovery': {
      id: '/app/refill/recovery'
      path: '/recovery'
      fullPath: '/app/refill/recovery'
      preLoaderRoute: typeof AppRefillRecoveryRouteImport
      parentRoute: typeof AppRefillRoute
    }
    '/app/refill/promos': {
      id: '/app/refill/promos'
      path: '/promos'
      fullPath: '/app/refill/promos'
      preLoaderRoute: typeof AppRefillPromosRouteImport
      parentRoute: typeof AppRefillRoute
    }
    '/app/refill/patients': {
      id: '/app/refill/patients'
      path: '/patients'
      fullPath: '/app/refill/patients'
      preLoaderRoute: typeof AppRefillPatientsRouteImport
      parentRoute: typeof AppRefillRoute
    }
    '/app/refill/inbox': {
      id: '/app/refill/inbox'
      path: '/inbox'
      fullPath: '/app/refill/inbox'
      preLoaderRoute: typeof AppRefillInboxRouteImport
      parentRoute: typeof AppRefillRoute
    }
    '/app/refill/health': {
      id: '/app/refill/health'
      path: '/health'
      fullPath: '/app/refill/health'
      preLoaderRoute: typeof AppRefillHealthRouteImport
      parentRoute: typeof AppRefillRoute
    }
    '/app/refill/campaigns': {
      id: '/app/refill/campaigns'
      path: '/campaigns'
      fullPath: '/app/refill/campaigns'
      preLoaderRoute: typeof AppRefillCampaignsRouteImport
      parentRoute: typeof AppRefillRoute
    }
    '/app/refill/billing': {
      id: '/app/refill/billing'
      path: '/billing'
      fullPath: '/app/refill/billing'
      preLoaderRoute: typeof AppRefillBillingRouteImport
      parentRoute: typeof AppRefillRoute
    }
    '/app/refill/appointments': {
      id: '/app/refill/appointments'
      path: '/appointments'
      fullPath: '/app/refill/appointments'
      preLoaderRoute: typeof AppRefillAppointmentsRouteImport
      parentRoute: typeof AppRefillRoute
    }
    '/app/admin/wishlist': {
      id: '/app/admin/wishlist'
      path: '/admin/wishlist'
      fullPath: '/app/admin/wishlist'
      preLoaderRoute: typeof AppAdminWishlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/reports': {
      id: '/app/admin/reports'
      path: '/admin/reports'
      fullPath: '/app/admin/reports'
      preLoaderRoute: typeof AppAdminReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/refill-trials': {
      id: '/app/admin/refill-trials'
      path: '/admin/refill-trials'
      fullPath: '/app/admin/refill-trials'
      preLoaderRoute: typeof AppAdminRefillTrialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/outreach': {
      id: '/app/admin/outreach'
      path: '/admin/outreach'
      fullPath: '/app/admin/outreach'
      preLoaderRoute: typeof AppAdminOutreachRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/flags': {
      id: '/app/admin/flags'
      path: '/admin/flags'
      fullPath: '/app/admin/flags'
      preLoaderRoute: typeof AppAdminFlagsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/canonical-brands': {
      id: '/app/admin/canonical-brands'
      path: '/admin/canonical-brands'
      fullPath: '/app/admin/canonical-brands'
      preLoaderRoute: typeof AppAdminCanonicalBrandsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/audit': {
      id: '/app/admin/audit'
      path: '/admin/audit'
      fullPath: '/app/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/inbound': {
      id: '/api/twilio/inbound'
      path: '/api/twilio/inbound'
      fullPath: '/api/twilio/inbound'
      preLoaderRoute: typeof ApiTwilioInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/refill-trial-drip': {
      id: '/api/cron/refill-trial-drip'
      path: '/api/cron/refill-trial-drip'
      fullPath: '/api/cron/refill-trial-drip'
      preLoaderRoute: typeof ApiCronRefillTrialDripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/refill-invoice': {
      id: '/api/cron/refill-invoice'
      path: '/api/cron/refill-invoice'
      fullPath: '/api/cron/refill-invoice'
      preLoaderRoute: typeof ApiCronRefillInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/emma-sweep': {
      id: '/api/cron/emma-sweep'
      path: '/api/cron/emma-sweep'
      fullPath: '/api/cron/emma-sweep'
      preLoaderRoute: typeof ApiCronEmmaSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/emma-reliability-sweep': {
      id: '/api/cron/emma-reliability-sweep'
      path: '/api/cron/emma-reliability-sweep'
      fullPath: '/api/cron/emma-reliability-sweep'
      preLoaderRoute: typeof ApiCronEmmaReliabilitySweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/emma-reconcile': {
      id: '/api/cron/emma-reconcile'
      path: '/api/cron/emma-reconcile'
      fullPath: '/api/cron/emma-reconcile'
      preLoaderRoute: typeof ApiCronEmmaReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/emma-recommendations': {
      id: '/api/cron/emma-recommendations'
      path: '/api/cron/emma-recommendations'
      fullPath: '/api/cron/emma-recommendations'
      preLoaderRoute: typeof ApiCronEmmaRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/emma-preshow-sweep': {
      id: '/api/cron/emma-preshow-sweep'
      path: '/api/cron/emma-preshow-sweep'
      fullPath: '/api/cron/emma-preshow-sweep'
      preLoaderRoute: typeof ApiCronEmmaPreshowSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/emma-invoice': {
      id: '/api/cron/emma-invoice'
      path: '/api/cron/emma-invoice'
      fullPath: '/api/cron/emma-invoice'
      preLoaderRoute: typeof ApiCronEmmaInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/refill/patients/': {
      id: '/app/refill/patients/'
      path: '/'
      fullPath: '/app/refill/patients/'
      preLoaderRoute: typeof AppRefillPatientsIndexRouteImport
      parentRoute: typeof AppRefillPatientsRoute
    }
    '/app/refill/campaigns/': {
      id: '/app/refill/campaigns/'
      path: '/'
      fullPath: '/app/refill/campaigns/'
      preLoaderRoute: typeof AppRefillCampaignsIndexRouteImport
      parentRoute: typeof AppRefillCampaignsRoute
    }
    '/app/refill/waitlist/seed': {
      id: '/app/refill/waitlist/seed'
      path: '/waitlist/seed'
      fullPath: '/app/refill/waitlist/seed'
      preLoaderRoute: typeof AppRefillWaitlistSeedRouteImport
      parentRoute: typeof AppRefillRoute
    }
    '/app/refill/waitlist/invite': {
      id: '/app/refill/waitlist/invite'
      path: '/waitlist/invite'
      fullPath: '/app/refill/waitlist/invite'
      preLoaderRoute: typeof AppRefillWaitlistInviteRouteImport
      parentRoute: typeof AppRefillRoute
    }
    '/app/refill/waitlist/bulk': {
      id: '/app/refill/waitlist/bulk'
      path: '/waitlist/bulk'
      fullPath: '/app/refill/waitlist/bulk'
      preLoaderRoute: typeof AppRefillWaitlistBulkRouteImport
      parentRoute: typeof AppRefillRoute
    }
    '/app/refill/settings/spa-profile': {
      id: '/app/refill/settings/spa-profile'
      path: '/settings/spa-profile'
      fullPath: '/app/refill/settings/spa-profile'
      preLoaderRoute: typeof AppRefillSettingsSpaProfileRouteImport
      parentRoute: typeof AppRefillRoute
    }
    '/app/refill/settings/sender': {
      id: '/app/refill/settings/sender'
      path: '/settings/sender'
      fullPath: '/app/refill/settings/sender'
      preLoaderRoute: typeof AppRefillSettingsSenderRouteImport
      parentRoute: typeof AppRefillRoute
    }
    '/app/refill/settings/scheduler': {
      id: '/app/refill/settings/scheduler'
      path: '/settings/scheduler'
      fullPath: '/app/refill/settings/scheduler'
      preLoaderRoute: typeof AppRefillSettingsSchedulerRouteImport
      parentRoute: typeof AppRefillRoute
    }
    '/app/refill/settings/noshow': {
      id: '/app/refill/settings/noshow'
      path: '/settings/noshow'
      fullPath: '/app/refill/settings/noshow'
      preLoaderRoute: typeof AppRefillSettingsNoshowRouteImport
      parentRoute: typeof AppRefillRoute
    }
    '/app/refill/settings/account': {
      id: '/app/refill/settings/account'
      path: '/settings/account'
      fullPath: '/app/refill/settings/account'
      preLoaderRoute: typeof AppRefillSettingsAccountRouteImport
      parentRoute: typeof AppRefillRoute
    }
    '/app/refill/patients/import': {
      id: '/app/refill/patients/import'
      path: '/import'
      fullPath: '/app/refill/patients/import'
      preLoaderRoute: typeof AppRefillPatientsImportRouteImport
      parentRoute: typeof AppRefillPatientsRoute
    }
    '/app/refill/patients/contacts': {
      id: '/app/refill/patients/contacts'
      path: '/contacts'
      fullPath: '/app/refill/patients/contacts'
      preLoaderRoute: typeof AppRefillPatientsContactsRouteImport
      parentRoute: typeof AppRefillPatientsRoute
    }
    '/app/refill/patients/a-list-rules': {
      id: '/app/refill/patients/a-list-rules'
      path: '/a-list-rules'
      fullPath: '/app/refill/patients/a-list-rules'
      preLoaderRoute: typeof AppRefillPatientsAListRulesRouteImport
      parentRoute: typeof AppRefillPatientsRoute
    }
    '/app/refill/patients/$patientId': {
      id: '/app/refill/patients/$patientId'
      path: '/$patientId'
      fullPath: '/app/refill/patients/$patientId'
      preLoaderRoute: typeof AppRefillPatientsPatientIdRouteImport
      parentRoute: typeof AppRefillPatientsRoute
    }
    '/app/refill/catalog/services': {
      id: '/app/refill/catalog/services'
      path: '/catalog/services'
      fullPath: '/app/refill/catalog/services'
      preLoaderRoute: typeof AppRefillCatalogServicesRouteImport
      parentRoute: typeof AppRefillRoute
    }
    '/app/refill/catalog/products': {
      id: '/app/refill/catalog/products'
      path: '/catalog/products'
      fullPath: '/app/refill/catalog/products'
      preLoaderRoute: typeof AppRefillCatalogProductsRouteImport
      parentRoute: typeof AppRefillRoute
    }
    '/app/refill/catalog/import': {
      id: '/app/refill/catalog/import'
      path: '/catalog/import'
      fullPath: '/app/refill/catalog/import'
      preLoaderRoute: typeof AppRefillCatalogImportRouteImport
      parentRoute: typeof AppRefillRoute
    }
    '/app/refill/campaigns/new': {
      id: '/app/refill/campaigns/new'
      path: '/new'
      fullPath: '/app/refill/campaigns/new'
      preLoaderRoute: typeof AppRefillCampaignsNewRouteImport
      parentRoute: typeof AppRefillCampaignsRoute
    }
    '/app/refill/campaigns/$campaignId': {
      id: '/app/refill/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/app/refill/campaigns/$campaignId'
      preLoaderRoute: typeof AppRefillCampaignsCampaignIdRouteImport
      parentRoute: typeof AppRefillCampaignsRoute
    }
    '/api/integrations/acuity/oauth-callback': {
      id: '/api/integrations/acuity/oauth-callback'
      path: '/api/integrations/acuity/oauth-callback'
      fullPath: '/api/integrations/acuity/oauth-callback'
      preLoaderRoute: typeof ApiIntegrationsAcuityOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/refill/campaigns/$campaignId/': {
      id: '/app/refill/campaigns/$campaignId/'
      path: '/'
      fullPath: '/app/refill/campaigns/$campaignId/'
      preLoaderRoute: typeof AppRefillCampaignsCampaignIdIndexRouteImport
      parentRoute: typeof AppRefillCampaignsCampaignIdRoute
    }
    '/app/refill/campaigns/$campaignId/blast': {
      id: '/app/refill/campaigns/$campaignId/blast'
      path: '/blast'
      fullPath: '/app/refill/campaigns/$campaignId/blast'
      preLoaderRoute: typeof AppRefillCampaignsCampaignIdBlastRouteImport
      parentRoute: typeof AppRefillCampaignsCampaignIdRoute
    }
    '/api/webhooks/scheduler/acuity/$secret': {
      id: '/api/webhooks/scheduler/acuity/$secret'
      path: '/api/webhooks/scheduler/acuity/$secret'
      fullPath: '/api/webhooks/scheduler/acuity/$secret'
      preLoaderRoute: typeof ApiWebhooksSchedulerAcuitySecretRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRefillCampaignsCampaignIdRouteChildren {
  AppRefillCampaignsCampaignIdBlastRoute: typeof AppRefillCampaignsCampaignIdBlastRoute
  AppRefillCampaignsCampaignIdIndexRoute: typeof AppRefillCampaignsCampaignIdIndexRoute
}

const AppRefillCampaignsCampaignIdRouteChildren: AppRefillCampaignsCampaignIdRouteChildren =
  {
    AppRefillCampaignsCampaignIdBlastRoute:
      AppRefillCampaignsCampaignIdBlastRoute,
    AppRefillCampaignsCampaignIdIndexRoute:
      AppRefillCampaignsCampaignIdIndexRoute,
  }

const AppRefillCampaignsCampaignIdRouteWithChildren =
  AppRefillCampaignsCampaignIdRoute._addFileChildren(
    AppRefillCampaignsCampaignIdRouteChildren,
  )

interface AppRefillCampaignsRouteChildren {
  AppRefillCampaignsCampaignIdRoute: typeof AppRefillCampaignsCampaignIdRouteWithChildren
  AppRefillCampaignsNewRoute: typeof AppRefillCampaignsNewRoute
  AppRefillCampaignsIndexRoute: typeof AppRefillCampaignsIndexRoute
}

const AppRefillCampaignsRouteChildren: AppRefillCampaignsRouteChildren = {
  AppRefillCampaignsCampaignIdRoute:
    AppRefillCampaignsCampaignIdRouteWithChildren,
  AppRefillCampaignsNewRoute: AppRefillCampaignsNewRoute,
  AppRefillCampaignsIndexRoute: AppRefillCampaignsIndexRoute,
}

const AppRefillCampaignsRouteWithChildren =
  AppRefillCampaignsRoute._addFileChildren(AppRefillCampaignsRouteChildren)

interface AppRefillPatientsRouteChildren {
  AppRefillPatientsPatientIdRoute: typeof AppRefillPatientsPatientIdRoute
  AppRefillPatientsAListRulesRoute: typeof AppRefillPatientsAListRulesRoute
  AppRefillPatientsContactsRoute: typeof AppRefillPatientsContactsRoute
  AppRefillPatientsImportRoute: typeof AppRefillPatientsImportRoute
  AppRefillPatientsIndexRoute: typeof AppRefillPatientsIndexRoute
}

const AppRefillPatientsRouteChildren: AppRefillPatientsRouteChildren = {
  AppRefillPatientsPatientIdRoute: AppRefillPatientsPatientIdRoute,
  AppRefillPatientsAListRulesRoute: AppRefillPatientsAListRulesRoute,
  AppRefillPatientsContactsRoute: AppRefillPatientsContactsRoute,
  AppRefillPatientsImportRoute: AppRefillPatientsImportRoute,
  AppRefillPatientsIndexRoute: AppRefillPatientsIndexRoute,
}

const AppRefillPatientsRouteWithChildren =
  AppRefillPatientsRoute._addFileChildren(AppRefillPatientsRouteChildren)

interface AppRefillRouteChildren {
  AppRefillAppointmentsRoute: typeof AppRefillAppointmentsRoute
  AppRefillBillingRoute: typeof AppRefillBillingRoute
  AppRefillCampaignsRoute: typeof AppRefillCampaignsRouteWithChildren
  AppRefillHealthRoute: typeof AppRefillHealthRoute
  AppRefillInboxRoute: typeof AppRefillInboxRoute
  AppRefillPatientsRoute: typeof AppRefillPatientsRouteWithChildren
  AppRefillPromosRoute: typeof AppRefillPromosRoute
  AppRefillRecoveryRoute: typeof AppRefillRecoveryRoute
  AppRefillReportsRoute: typeof AppRefillReportsRoute
  AppRefillRescueRoute: typeof AppRefillRescueRoute
  AppRefillSharingRoute: typeof AppRefillSharingRoute
  AppRefillIndexRoute: typeof AppRefillIndexRoute
  AppRefillCatalogImportRoute: typeof AppRefillCatalogImportRoute
  AppRefillCatalogProductsRoute: typeof AppRefillCatalogProductsRoute
  AppRefillCatalogServicesRoute: typeof AppRefillCatalogServicesRoute
  AppRefillSettingsAccountRoute: typeof AppRefillSettingsAccountRoute
  AppRefillSettingsNoshowRoute: typeof AppRefillSettingsNoshowRoute
  AppRefillSettingsSchedulerRoute: typeof AppRefillSettingsSchedulerRoute
  AppRefillSettingsSenderRoute: typeof AppRefillSettingsSenderRoute
  AppRefillSettingsSpaProfileRoute: typeof AppRefillSettingsSpaProfileRoute
  AppRefillWaitlistBulkRoute: typeof AppRefillWaitlistBulkRoute
  AppRefillWaitlistInviteRoute: typeof AppRefillWaitlistInviteRoute
  AppRefillWaitlistSeedRoute: typeof AppRefillWaitlistSeedRoute
}

const AppRefillRouteChildren: AppRefillRouteChildren = {
  AppRefillAppointmentsRoute: AppRefillAppointmentsRoute,
  AppRefillBillingRoute: AppRefillBillingRoute,
  AppRefillCampaignsRoute: AppRefillCampaignsRouteWithChildren,
  AppRefillHealthRoute: AppRefillHealthRoute,
  AppRefillInboxRoute: AppRefillInboxRoute,
  AppRefillPatientsRoute: AppRefillPatientsRouteWithChildren,
  AppRefillPromosRoute: AppRefillPromosRoute,
  AppRefillRecoveryRoute: AppRefillRecoveryRoute,
  AppRefillReportsRoute: AppRefillReportsRoute,
  AppRefillRescueRoute: AppRefillRescueRoute,
  AppRefillSharingRoute: AppRefillSharingRoute,
  AppRefillIndexRoute: AppRefillIndexRoute,
  AppRefillCatalogImportRoute: AppRefillCatalogImportRoute,
  AppRefillCatalogProductsRoute: AppRefillCatalogProductsRoute,
  AppRefillCatalogServicesRoute: AppRefillCatalogServicesRoute,
  AppRefillSettingsAccountRoute: AppRefillSettingsAccountRoute,
  AppRefillSettingsNoshowRoute: AppRefillSettingsNoshowRoute,
  AppRefillSettingsSchedulerRoute: AppRefillSettingsSchedulerRoute,
  AppRefillSettingsSenderRoute: AppRefillSettingsSenderRoute,
  AppRefillSettingsSpaProfileRoute: AppRefillSettingsSpaProfileRoute,
  AppRefillWaitlistBulkRoute: AppRefillWaitlistBulkRoute,
  AppRefillWaitlistInviteRoute: AppRefillWaitlistInviteRoute,
  AppRefillWaitlistSeedRoute: AppRefillWaitlistSeedRoute,
}

const AppRefillRouteWithChildren = AppRefillRoute._addFileChildren(
  AppRefillRouteChildren,
)

interface AppRepRouteChildren {
  AppRepEconomicsRoute: typeof AppRepEconomicsRoute
  AppRepIntegrationsRoute: typeof AppRepIntegrationsRoute
  AppRepLedgerRoute: typeof AppRepLedgerRoute
  AppRepNetworkRoute: typeof AppRepNetworkRoute
  AppRepOutreachRoute: typeof AppRepOutreachRoute
  AppRepRecruitRoute: typeof AppRepRecruitRoute
  AppRepReferralLinksRoute: typeof AppRepReferralLinksRoute
  AppRepIndexRoute: typeof AppRepIndexRoute
}

const AppRepRouteChildren: AppRepRouteChildren = {
  AppRepEconomicsRoute: AppRepEconomicsRoute,
  AppRepIntegrationsRoute: AppRepIntegrationsRoute,
  AppRepLedgerRoute: AppRepLedgerRoute,
  AppRepNetworkRoute: AppRepNetworkRoute,
  AppRepOutreachRoute: AppRepOutreachRoute,
  AppRepRecruitRoute: AppRepRecruitRoute,
  AppRepReferralLinksRoute: AppRepReferralLinksRoute,
  AppRepIndexRoute: AppRepIndexRoute,
}

const AppRepRouteWithChildren =
  AppRepRoute._addFileChildren(AppRepRouteChildren)

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppRefillRoute: typeof AppRefillRouteWithChildren
  AppRepRoute: typeof AppRepRouteWithChildren
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminCanonicalBrandsRoute: typeof AppAdminCanonicalBrandsRoute
  AppAdminFlagsRoute: typeof AppAdminFlagsRoute
  AppAdminOutreachRoute: typeof AppAdminOutreachRoute
  AppAdminRefillTrialsRoute: typeof AppAdminRefillTrialsRoute
  AppAdminReportsRoute: typeof AppAdminReportsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminWishlistRoute: typeof AppAdminWishlistRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppRefillRoute: AppRefillRouteWithChildren,
  AppRepRoute: AppRepRouteWithChildren,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminCanonicalBrandsRoute: AppAdminCanonicalBrandsRoute,
  AppAdminFlagsRoute: AppAdminFlagsRoute,
  AppAdminOutreachRoute: AppAdminOutreachRoute,
  AppAdminRefillTrialsRoute: AppAdminRefillTrialsRoute,
  AppAdminReportsRoute: AppAdminReportsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminWishlistRoute: AppAdminWishlistRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BookRoute: BookRoute,
  ClaimYourBusinessRoute: ClaimYourBusinessRoute,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScanRoute: ScanRoute,
  StartRoute: StartRoute,
  StoryRoute: StoryRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ApiRefillCheckoutRoute: ApiRefillCheckoutRoute,
  ApiRefillPortalRoute: ApiRefillPortalRoute,
  RSlugRoute: RSlugRoute,
  ReportTokenRoute: ReportTokenRoute,
  ApiCronEmmaInvoiceRoute: ApiCronEmmaInvoiceRoute,
  ApiCronEmmaPreshowSweepRoute: ApiCronEmmaPreshowSweepRoute,
  ApiCronEmmaRecommendationsRoute: ApiCronEmmaRecommendationsRoute,
  ApiCronEmmaReconcileRoute: ApiCronEmmaReconcileRoute,
  ApiCronEmmaReliabilitySweepRoute: ApiCronEmmaReliabilitySweepRoute,
  ApiCronEmmaSweepRoute: ApiCronEmmaSweepRoute,
  ApiCronRefillInvoiceRoute: ApiCronRefillInvoiceRoute,
  ApiCronRefillTrialDripRoute: ApiCronRefillTrialDripRoute,
  ApiTwilioInboundRoute: ApiTwilioInboundRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  RescueClaimTokenRoute: RescueClaimTokenRoute,
  WaitlistOptinTokenRoute: WaitlistOptinTokenRoute,
  ApiIntegrationsAcuityOauthCallbackRoute:
    ApiIntegrationsAcuityOauthCallbackRoute,
  ApiWebhooksSchedulerAcuitySecretRoute: ApiWebhooksSchedulerAcuitySecretRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
