-- v391: Refill customer-side billing — Phase 1.6 slice 4 (billing engine begins).
--
-- The conversion engine reaches the money flow. v388–v390 shipped the
-- engagement drip + reply capture + incentive lever board. v391 ships the
-- backend foundation for Stripe-metered billing: schema, idempotency,
-- Refill-side webhook event routing. UI (Stripe Elements payment method
-- capture + plan picker) lands in v391.1; admin visibility + monthly invoice
-- cron lands in v391.2.
--
-- Per [[project_trial_first_no_money_asks]] no spa is asked for money until
-- the trial WIN has landed. This migration just stands up the substrate so
-- when the spa is ready, the plan-pick → payment-method → first-invoice flow
-- has somewhere to write.
--
-- Four schema changes:
--
--   refill_pricing_plans   — per-tenant plan selection (mirrors emma_pricing_plans
--                            but tenant-scoped; one active row per tenant_id at
--                            a time; full history preserved on plan change for
--                            audit).
--
--   refill_invoices        — monthly billing records per (tenant, month).
--                            Generated by v391.2 cron. Ships in 'draft' status;
--                            Stripe push activates when stripe_customer_id is
--                            non-null on the pricing plan row.
--
--   tenants.stripe_customer_id  — ALTER. Stripe customer identity lives on the
--                            tenant row because it's a stable per-spa identity
--                            that outlives plan changes. Mirrors the killshot
--                            doc's "spa = tenant" identity model.
--
--   stripe_webhook_events  — idempotency table for the shared Stripe webhook
--                            (supabase/functions/stripe-webhook). Inserted at
--                            the top of the handler with ON CONFLICT on
--                            stripe_event_id; if conflict, handler returns 200
--                            immediately. Retrofitted to cover ALL existing
--                            paths (Emma platform subs, payouts, revenue_events
--                            in the WCS engine), not just Refill — the existing
--                            revenue_events insert path has been leaking
--                            duplicates on Stripe retries (no unique constraint
--                            on stripe_event_id inside the metadata jsonb).
--
-- Three Refill pricing plans (codified in src/server/refill-billing.functions.ts
-- as PLAN_ECONOMICS; this migration only validates the values):
--
--   starter      — free + 12% of recovered revenue (the killshot default;
--                  aligns incentives — spa only pays when recovery revenue
--                  arrives)
--   pro          — $99/mo + 8% of recovered (commitment + shared upside)
--
-- ('trial' is NOT a refill_pricing_plans value — it's the absence of a paid
--  plan, encoded by tenants.plan='trial' on the tenant row. A pricing-plans
--  row only exists once the spa has explicitly picked a paid plan post-trial.)
--
-- RLS posture matches the Phase 1.5 tenants migration: service-role only, no
-- user policies. Phase 4 will add per-table tenant-membership-scoped policies
-- across all Refill tables in one coherent sweep. Until then, all access is
-- mediated through server functions that gate on auth + tenant_memberships.

-- ── refill_pricing_plans ────────────────────────────────────────────────

create table if not exists public.refill_pricing_plans (
  id                       uuid        primary key default gen_random_uuid(),
  tenant_id                uuid        not null references public.tenants(id) on delete cascade,

  plan                     text        not null
                           check (plan in ('starter', 'pro')),

  -- Economic parameters snapshotted at plan-selection time so a future
  -- price change doesn't retroactively alter past invoices.
  revenue_share_pct        numeric(5,4)  not null default 0,  -- 0..1 (0.12 = 12%)
  monthly_flat_usd         numeric(10,2) not null default 0,

  -- Lifecycle. A tenant has at most one row with plan_ended_at=null at a
  -- time (the active plan). Plan changes write a new row + close the prior.
  plan_started_at          timestamptz not null default now(),
  plan_ended_at            timestamptz,

  -- Stripe customer linkage on the plan row for symmetry with Emma's pattern.
  -- The authoritative copy lives on tenants.stripe_customer_id (per-spa
  -- identity); this column is a denormalization the v391.1 UI fills in at
  -- payment-method-capture time so the billing-page query is one round-trip.
  -- Phase 4 may drop in favor of joining through tenants.
  stripe_customer_id       text,

  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);

alter table public.refill_pricing_plans enable row level security;

do $$ begin
  create policy "service_role_refill_pricing_plans"
    on public.refill_pricing_plans for all
    using  (auth.role() = 'service_role')
    with check (auth.role() = 'service_role');
exception when duplicate_object then null;
end $$;

create index if not exists refill_pricing_plans_active_idx
  on public.refill_pricing_plans (tenant_id)
  where plan_ended_at is null;

create trigger refill_pricing_plans_set_updated_at
  before update on public.refill_pricing_plans
  for each row execute function public.set_updated_at();

comment on table public.refill_pricing_plans is
  'Per-tenant Refill pricing plan selection. One active row (plan_ended_at=null) per tenant_id at a time; historical rows preserved on plan change. Plan economics snapshotted at selection so future price changes don''t alter past invoices.';

-- ── refill_invoices ─────────────────────────────────────────────────────

create table if not exists public.refill_invoices (
  id                       uuid        primary key default gen_random_uuid(),
  tenant_id                uuid        not null references public.tenants(id) on delete cascade,

  -- Billing period. period_start = 1st of month at 00:00 UTC; period_end =
  -- 1st of the next month (exclusive).
  period_start             timestamptz not null,
  period_end               timestamptz not null,

  -- Plan snapshot at invoice time (future plan changes don't rewrite
  -- historical invoices).
  plan_at_invoice          text        not null,
  revenue_share_pct        numeric(5,4) not null,
  monthly_flat_usd         numeric(10,2) not null,

  -- Math. recovered_revenue_usd is the sum of verified recovery events in
  -- the period; share_due_usd = recovered * pct; total_due_usd = share + flat.
  recovered_revenue_count  integer     not null default 0,
  recovered_revenue_usd    numeric(12,2) not null default 0,
  share_due_usd            numeric(12,2) not null default 0,
  total_due_usd            numeric(12,2) not null default 0,

  status                   text        not null default 'draft'
                           check (status in (
                             'draft',         -- generated but not pushed
                             'sent',          -- pushed to Stripe
                             'paid',          -- Stripe paid
                             'failed',        -- payment failed
                             'void'           -- spa cancelled/disputed
                           )),

  stripe_invoice_id        text,

  generated_at             timestamptz not null default now(),
  sent_at                  timestamptz,
  paid_at                  timestamptz,
  voided_at                timestamptz,
  voided_by                text,
  notes                    text,

  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),

  -- One invoice per (tenant, month).
  unique (tenant_id, period_start)
);

alter table public.refill_invoices enable row level security;

do $$ begin
  create policy "service_role_refill_invoices"
    on public.refill_invoices for all
    using  (auth.role() = 'service_role')
    with check (auth.role() = 'service_role');
exception when duplicate_object then null;
end $$;

create index if not exists refill_invoices_by_tenant_idx
  on public.refill_invoices (tenant_id, period_start desc);

create index if not exists refill_invoices_by_status_idx
  on public.refill_invoices (tenant_id, status)
  where status in ('draft', 'sent', 'failed');

create trigger refill_invoices_set_updated_at
  before update on public.refill_invoices
  for each row execute function public.set_updated_at();

comment on table public.refill_invoices is
  'Monthly billing record per (tenant, month). Generated by the v391.2 cron from verified emma_recovery_events scoped to the tenant''s user_id(s). Ships in draft status — activates Stripe push when refill_pricing_plans.stripe_customer_id is non-null.';

-- ── tenants.stripe_customer_id (the per-spa identity, stable across plans) ─

alter table public.tenants
  add column if not exists stripe_customer_id text;

create index if not exists tenants_stripe_customer_idx
  on public.tenants (stripe_customer_id)
  where stripe_customer_id is not null;

comment on column public.tenants.stripe_customer_id is
  'Stripe customer id (cus_xxx) for this spa. Stable per-tenant identity that outlives plan changes — created once at first payment-method capture (v391.1) and reused across every subscription, plan switch, and invoice. Indexed for webhook reverse-lookup (customer.subscription.updated and friends).';

-- ── stripe_webhook_events (idempotency for the shared Stripe webhook) ─────

create table if not exists public.stripe_webhook_events (
  id                       uuid        primary key default gen_random_uuid(),

  -- The Stripe event id (evt_xxx). Unique even on Stripe retries — this is
  -- the dedup key. Inserted at the top of the webhook handler with
  -- ON CONFLICT DO NOTHING. If the insert fails (conflict), the handler
  -- returns 200 immediately and skips all branches.
  stripe_event_id          text        not null unique,

  event_type               text        not null,

  -- Which product processed this event. 'platform' = existing user_subscriptions
  -- flow; 'wcs' = the revenue_events/revenue_shares creator-share flow;
  -- 'refill' = v391+ tenant-scoped subs; 'emma' reserved for v366.x activation.
  -- Populated by the handler so we can answer 'how many duplicate webhooks
  -- did we suppress for product X this month' without a metadata jsonb scan.
  product                  text,

  received_at              timestamptz not null default now(),
  processed_at             timestamptz,

  -- 'received' on first insert; 'processed' once the handler finishes its
  -- branch successfully; 'failed' if an exception propagates; never set to
  -- 'duplicate' from the handler (a duplicate is denoted by the absence of
  -- a second row — the unique constraint prevents the insert).
  status                   text        not null default 'received'
                           check (status in ('received', 'processed', 'failed')),

  error_message            text,

  -- Full event payload for forensic replay. Keeping it on the row (rather
  -- than fetching from Stripe API later) costs ~5 KB/event but is
  -- invaluable when Stripe rotates a customer id under us or we need to
  -- prove we received an event that the Stripe dashboard claims we didn't.
  payload                  jsonb,

  created_at               timestamptz not null default now()
);

alter table public.stripe_webhook_events enable row level security;

do $$ begin
  create policy "service_role_stripe_webhook_events"
    on public.stripe_webhook_events for all
    using  (auth.role() = 'service_role')
    with check (auth.role() = 'service_role');
exception when duplicate_object then null;
end $$;

create index if not exists stripe_webhook_events_received_idx
  on public.stripe_webhook_events (received_at desc);

create index if not exists stripe_webhook_events_status_idx
  on public.stripe_webhook_events (status)
  where status in ('received', 'failed');

comment on table public.stripe_webhook_events is
  'Idempotency + forensic log for the shared Stripe webhook (supabase/functions/stripe-webhook). Insert at top of handler with ON CONFLICT on stripe_event_id; conflict means duplicate retry from Stripe, return 200 and skip branches. Retrofitted for all product paths in v391, not just Refill.';

-- ── PostgREST schema reload (for type generation downstream) ─────────────

notify pgrst, 'reload schema';

-- ── Verify (paste-friendly) ──────────────────────────────────────────────
-- Run these in the SQL editor after the migration completes to confirm the
-- four schema changes landed cleanly.
--
-- select table_name, column_name, data_type
--   from information_schema.columns
--  where table_schema = 'public'
--    and table_name in (
--      'refill_pricing_plans',
--      'refill_invoices',
--      'stripe_webhook_events'
--    )
--  order by table_name, ordinal_position;
--
-- select column_name from information_schema.columns
--  where table_schema='public' and table_name='tenants'
--    and column_name='stripe_customer_id';
--
-- select indexname from pg_indexes
--  where schemaname='public'
--    and tablename in ('refill_pricing_plans','refill_invoices','stripe_webhook_events','tenants');
